---
- name: Configure repo.
  hosts: servers
  roles:
    - role: ansible-role-repo-lan
      repo_lan_repos:
        - { name: "base", baseurl:  "http://mirrors.ustc.edu.cn/centos/7/os/x86_64/" }
        - { name: "extras", baseurl: "http://mirrors.ustc.edu.cn/centos/7/extras/x86_64/" }
